// ACTIONS
export const RECEIVE_BET = 'RECEIVE_BET';
export const RECEIVE_CURRENT_BET = 'RECEIVE_CURRENT_BET';
export const RECEIVE_BET_ERROR = 'RECEIVE_BET_ERROR';
export const RECEIVE_COMMISSION = 'RECEIVE_COMMISSION';
export const RECEIVE_COMMISSION_ERROR = 'RECEIVE_CURRENT_COMMISSION';
export const RECEIVE_CURRENT_RESULTS = 'RECEIVE_CURRENT_RESULTS';
export const RECEIVE_RESULTS_ERROR = 'RECEIVE_RESULTS_ERROR';
export const RECEIVE_DIVIDENDS = 'RECEIVE_DIVIDENDS';
